8/김진/로그인페이지 제작
junjeeong/9_3_Wikid pull request #131
Opened 2024-10-30 07:17 UTC by jjeankim

2024-10-30 08:18 UTC, DrowsyzzZ requested changes

2024-10-30 08:18 UTC, DrowsyzzZ commented on src/pages/login/index.tsx
> +        router.push(`/wiki/${user.profile.name}`);
user.name 으로 해주셔야 합니다!! 
user.profile 에는 id랑 code 값만 들어있어요!

2024-10-30 08:20 UTC, jjeankim commented on src/pages/login/index.tsx
> +        router.push(`/wiki/${user.profile.name}`);
음...제가  authstore에 프로필 업데이트 함수 추가하면서 그 시점부터는 생성하면 이름도 들어가는데 혹시...안되려나요?

2024-10-30 13:18 UTC, DrowsyzzZ approved these changes
수정해주셨네요 😊

2024-10-31 03:22 UTC, venise5224 approved these changes

2024-10-31 04:51 UTC, closed without merging