Fix : Quiz-settings 페이지 경로 변경
junjeeong/9_3_Wikid pull request #133
Opened 2024-10-30 09:04 UTC by jjeankim

### Quiz-settings 페이지 경로 변경

- user.profile.id => user.name 으로 변경
- authStore createProfile함수 삭제

2024-10-30 13:49 UTC, DrowsyzzZ requested changes

2024-10-30 13:49 UTC, DrowsyzzZ commented on src/store/AuthStore.tsx
> +  profile: null;
이러면 프로필에 null 값만 할당될 것 같아요! 수정해야 할 것 같습니다
```suggestion
  interface LoginProfile {
    id: number;
    code: string;
  }
  
  interface User extends LoginProfile {
    id: number;
    ...
  }
  // 혹은 profile: LoginProfile | null;
```

2024-10-30 13:58 UTC, jjeankim commented on src/store/AuthStore.tsx
> +  profile: null;
앗 수정했습니다.

2024-10-31 05:36 UTC, junjeeong approved these changes

2024-10-31 05:37 UTC, DrowsyzzZ approved these changes

2024-10-31 05:37 UTC, venise5224 approved these changes

2024-10-31 05:37 UTC, merged